### ISSUE TITLE
Saving Information to Tables in Database Trouble

### ISSUE THREAD

**Issue by BowenSkylar** [BowenSkylar/VapeNique#1]
Good Morning Guys,

So I've spent the entire weekend trying to wrap my head around what I should do.

What I am trying to do is save my information into the database. The form is being sent into two different directions and I am kind of starting to panic.Ive tried inserting dummy data into my database and tables, but cannot figure out how to save from forms. I know how to psql query ALL columns to every table but dont know if this s the correct approach. I feel a little lost in my code but this could just be because ive been at the same road block.

I think one I get my information to save into the database it will be fine, I believe i can render my results easier then saving them... If there is anyway you guys can help that would be awesome.
I have been also refrencing projects from later in the program but the refrence of them still doesnt help much for this specific task.

@trevorpreston
@irwintsay
@rapala61
@gittheking
@jasonseminara

**Comment by rapala61** [comment]
Fix ERDs as I showed you then ping me to keep troubleshooting.

**Comment by rapala61** [comment]
Now working on CRUD functionality with POSTMAN.

**Comment by trevorpreston** [comment]
Is this still active?  @rapala61 @BowenSkylar

**Comment by BowenSkylar** [comment]
Hey, Yeah im currently still working on this right now. Me and rafa have been in contact.

**Comment by trevorpreston** [comment]
Ok.  Rafa's got you!
