### ISSUE TITLE
Can only post to PostMan with manual inputs

### ISSUE THREAD

**Issue by BowenSkylar** [BowenSkylar/VapeNique#2]
Hi guys, I told Rafa I was advoiding making an issue ticket but this project is backfiring on me big time, at this rate I am completely off track from everything i had planned and im scared i wont finish in time to present anything working..

My issue consist of:  not being able to fire my post function to my database, but i can physically post to my db if i manually write everything out within POSTMAN.

I think it may be my JWT?

Things i've tried so far, targeting state which contains jason web token, but can not get information to pass to my database.

Also: I tried targeting my ingredients which are being rendered to an array within my state ( this is becasue of a feautre that allows you to just hit a (+) button and you can add another ingredient and measurement.

@trevorpreston
@irwintsay
@rapala61
@gittheking
@jasonseminara

**Comment by gittheking** [comment]
@BowenSkylar What errors are you seeing when posting to your database? include the code snippet of the `fetch` call **AND** the method used in your model to insert into your DB.

**Comment by BowenSkylar** [comment]
![screen shot 2016-12-13 at 2 30 54 pm](https://cloud.githubusercontent.com/assets/20446304/21155879/d4cef486-c141-11e6-8882-b28192cf8e3b.png)
^^ MODEL


![screen shot 2016-12-13 at 2 32 25 pm](https://cloud.githubusercontent.com/assets/20446304/21155888/d8e70f4a-c141-11e6-9736-7367107b3009.png)

ERROR^^

![screen shot 2016-12-13 at 2 34 35 pm](https://cloud.githubusercontent.com/assets/20446304/21155895/e1fc7688-c141-11e6-92c1-3fba39039fc0.png)
^DB BEFORE^


![screen shot 2016-12-13 at 2 37 49 pm](https://cloud.githubusercontent.com/assets/20446304/21155920/fb412d3c-c141-11e6-8668-1f7016ebf98a.png)
^^FETCH 





if i physically enter "Bearer (json web token here) and post via post man with user's ID manually entered as well VVVVVVVV
 
![screen shot 2016-12-13 at 2 36 29 pm](https://cloud.githubusercontent.com/assets/20446304/21155925/00460bea-c142-11e6-8878-b213ad115c88.png)
![screen shot 2016-12-13 at 2 38 02 pm](https://cloud.githubusercontent.com/assets/20446304/21155924/0045cbbc-c142-11e6-89d0-1e4c3b921fbb.png)
