### ISSUE TITLE
New Issue- Rendering from DB

### ISSUE THREAD

**Issue by BowenSkylar** [BowenSkylar/VapeNique#3]
Hello,

I'm still having a lot of trouble with my DB.
I've skipped trying to ave my ingredients for now, and am currently trying to display the correct information for each user when logged into the application.

Like before my same issue can be completed in PostMan but when i implement my 'fetch' call it throws an error.

the components are rendering but the information is not brought in from the DB via app, but will via postman GET method

ERROR: 
![screen shot 2016-12-14 at 11 36 37 am](https://cloud.githubusercontent.com/assets/20446304/21190941/9d9ab83c-c1f1-11e6-8819-be622e95247a.png)

@trevorpreston
@irwintsay
@rapala61
@gittheking
@mgershowitz

**Comment by trevorpreston** [comment]
queued
